### ISSUE TITLE
feature requrest: support IDN conversion

### ISSUE THREAD

**Issue by peetrike** [EvotecIT/DnsClientX#9]
It would be nice to have IDN [Punycode](https://www.rfc-editor.org/rfc/rfc3492.txt) conversion built in to DnsClientX.

**Comment by PrzemyslawKlys** [comment]
So I did add it in the PR, just wondering if that's the proper way. Whether this should be disabled by default and enabled on demand or vice versa. What would be the potential impact. 

Do other Clients support it?

**Comment by peetrike** [comment]
> Do other Clients support it?

- [Resolve-DnsName](https://learn.microsoft.com/powershell/module/dnsclient/resolve-dnsname) - No
- [Get-Dns](https://github.com/indented-automation/Indented.Net.Dns) - yes
